config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:new, :create, :show] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '日用品' },
    { id: 3, name: '食べ物' },
    { id: 4, name: '本' },
    { id: 5, name: '場所' },
    { id: 6, name: '趣味' },
    { id: 7, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category,:status

  validates :item_name, presence: true, unless: :was_attached?

  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"} 
  validates :status_id, numericality: { other_than: 1 , message: "can't be blank"} 
  validates :date, presence: true

  def was_attached?
    self.image.attached?
  end
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'オススメしたい' },
    { id: 3, name: 'オススメされた' },
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end


  private

  def item_params
    params.require(:item).permit(:image,:status_id,:item_name,:date,:category_id,:explanation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>
<body>
<div class='main'>
  <div class="item-contents">
      <h2 class="title">オススメアイテム一覧</h2>
      <ul class='item-lists'>

      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to  item_path(item) do %>
          <div class='item-img-content'>
           <%= image_tag item.image.variant(resize: '200x200'), class: "item-img" if item.image.attached? %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.item_name %>
            </h3>
            <div class='item-category'>
              <%= item.category.name %>
            </div>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
              </div>
            
          </div>
        <% end %> 
      </li>
      <% end %> 
    </ul>
  </div>
</div>
</body>

<%= link_to image_tag('register.png', size: '150x200' , class: 'register-btn'),'/items/new' %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('register.png' , size: '175x170'), "/" %>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">オススメアイテムを登録</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        アイテム画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="form-group">
        <div class="weight-bold-text">
          日付
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :date, class:"items-text", id:"item-name", placeholder:"(例)2023/04/01" %>

      <div class="weight-bold-text">
        アイテム名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"アイテム名（必須 40文字まで)" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          アイテムの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"アイテムの説明（必須 1,000文字まで）" ,rows:"7" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select( :category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          オススメ状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select( :status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>    
<main>
    <div class="left-content">
      <%= image_tag @item.image.variant(resize: '300x300') ,class:"item-box-img" %>
      <%# if @item.purchase != nil %>
      <%# end %>

        <%= link_to "商品の編集", root_path(@item), method: :get, class: "item-edit-btn" %>
        <%= link_to "削除", root_path(@item), method: :delete, class:"item-destroy-btn" %>
    </div>
  
    <div class="right-content">
      <div class="item-explain-box">      
          <%= @item.item_name %>
      </div>

      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-item">アイテム名</th>
            <td class="detail-value"><%= @item.item_name %></td>
          </tr>
          <tr>
            <th class="detail-item">カテゴリー</th>
            <td class="detail-value"><%= @item.category.name %></td>
          </tr>
          <tr>
            <th class="detail-item">日付</th>
            <td class="detail-value"><%= @item.date %></td>
          </tr>
        </tbody>
      </table>
            <div class="explanation-title">説明</div>
            <div class="explanation"><%= @item.explanation %></div>
          <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
    </div>
  </div>
</main>
  <%# /商品の概要 %>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>


<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memoly38802</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <%= link_to image_tag("icon.png", class:"logo-white"), "#" %>
  <p>© MEMOLY</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>

  <div class='search-bar-contents'>
    <%= link_to image_tag("icon.png", class:"memoly-icon"), "/" %>
      <form class="search-form" action="#">
        <input class='input-box' placeholder='キーワードから探す'>
          <button class="search-button">
            <%= image_tag "search.png", class:"search-icon" %>
          </button>
      </form>
  </div>

  <div class='nav'>
    
    <ul class='lists-right'>
      <li><%= link_to '★オススメしたい', "/users/sign_in", class: "recommend" %></li>
      <li><%= link_to '★オススメされた', "/users/sign_up", class: "recommended" %></li>
    </ul>

  </div>
</header>